Repository mash-up-kr/HikingClub_iOS, pull requests merged in 2021-12, with the labels that each got.

#99 [QA] 1차 devQA
  HikingClub.xcodeproj/project.pbxproj
  HikingClub/Feature/Login/SignUp/SignUpInputViewController.swift
  HikingClub/Feature/Login/SignUp/SignUpViewController.swift
  HikingClub/Feature/MyPage/View/MyPageList/MyPageListHeaderButtonView.swift
  HikingClub/Feature/Search/SearchCategoryResultViewController.swift
  HikingClub/Feature/Settings/SettingViewController.swift
  HikingClub/SupportingFiles/Info.plist
Labels: merge대기중⏱, 상훈🐬

#100 [Feature] 문의하기 기능 완료
  HikingClub.xcodeproj/project.pbxproj
  HikingClub/Feature/Settings/Inquiry/InquiryListCell.swift
  HikingClub/Feature/Settings/Inquiry/InquiryViewController.swift
  HikingClub/Feature/Settings/Inquiry/inquiryMenuViewModel.swift
  HikingClub/Feature/Settings/SettingViewController.swift
Labels: 상훈🐬, merge완료👍

#101 [Feature] 오픈소스 라이센스 완료
  HikingClub.xcodeproj/project.pbxproj
  HikingClub/Feature/Settings/OpenSourceLicnese/OpensourceLicenseViewController.swift
  HikingClub/Feature/Settings/SettingViewController.swift
  HikingClub/SupportingFiles/Resource/license.rtf
Labels: merge대기중⏱, 상훈🐬

#102 [QA] 회원 가입 성공 시 로그인 처리
  HikingClub.xcodeproj/project.pbxproj
  HikingClub/Feature/Login/SignUp/InitialSetting/InitialSettingViewModel.swift
  HikingClub/Network/Users/SignUpService/Response/SignUpResponseModel.swift
  HikingClub/Network/Users/SignUpService/SignUpService.swift
Labels: merge대기중⏱, 상훈🐬

#105 :bulb: 앱 최초시작 확인하기
  HikingClub.xcodeproj/project.pbxproj
  HikingClub/Feature/Home/HomeViewModel.swift
  HikingClub/Helper/Extension/UserDefault+.swift
  HikingClub/Helper/Manager/FirstUserManager.swift
  HikingClub/SupportingFiles/AppDelegate.swift
  HikingClub/SupportingFiles/SceneDelegate.swift
Labels: merge대기중⏱, 문정🦭

#108 :bulb: 태그앞에 #표시추가
  HikingClub/Feature/Home/View/Road/RoadHashTagView.swift
  HikingClub/Feature/Home/View/Road/TableViewCell/RoadTableViewCell.swift
Labels: merge대기중⏱, 남수🐢, QA🍗

#110 Qa/ns/road list image bug
  HikingClub/Feature/Home/HomeViewController.swift
  HikingClub/Feature/Home/View/Road/RoadHashTagView.swift
  HikingClub/Feature/Home/View/Road/TableViewCell/RoadTableViewCell.swift
  HikingClub/Feature/Home/View/Road/TableViewCell/RoadTableViewCell.xib
  HikingClub/Feature/Search/SearchCategoryResultViewController.swift
Labels: merge대기중⏱, 남수🐢, 긴급🚨

#111 Release/v1.0.1 -> Develop
  HikingClub.xcodeproj/project.pbxproj
Labels: 리뷰대기중⏰, 상훈🐬

#115 [Refactor] ViewModel에서 ToastMessage 노출 로직 변경
  HikingClub/Feature/ChangePassword/ChangePasswordViewModel.swift
  HikingClub/Feature/Login/SignIn/SignInViewModel.swift
  HikingClub/Feature/Login/SignUp/EmailAuthorize/EmailAuthorizeViewModel.swift
  HikingClub/Feature/Login/SignUp/InitialSetting/InitialSettingViewModel.swift
  HikingClub/Feature/Login/SignUp/SignUpViewController.swift
  HikingClub/Feature/MyPage/MyPageViewModel.swift
  HikingClub/Feature/SelectTown/SelectTownViewModel.swift
  HikingClub/Helper/BaseArchitecture/BaseViewController.swift
  HikingClub/Helper/BaseArchitecture/BaseViewModel.swift
Labels: 개발간 어려움 ✏️, 상훈🐬

#114 [Bug] 약관 동의 후, 약관페이지를 통한 약관동의 시 상태 업데이트 안되던 현상 대응
  HikingClub/Feature/Login/SignUp/SignUpViewController.swift
Labels: 버그 🐛, 상훈🐬, 리뷰완료😎

#117 [Bug] 약관 동의 후, 약관페이지를 통한 약관동의 시 상태 업데이트 안되던 현상 대응
  HikingClub/Feature/Login/SignUp/SignUpViewController.swift
Labels: 피드백반영완료🙆🏻‍♂️, 상훈🐬, 리뷰완료😎

#118 :recycle: 이미지 레이아웃 개선
  HikingClub/Feature/Home/HomeViewController.swift
  HikingClub/Feature/Home/View/Road/TableViewCell/RoadTableViewCell.swift
  HikingClub/Feature/Home/View/Road/TableViewCell/RoadTableViewCell.xib
  HikingClub/Feature/Search/SearchCategoryResultViewController.swift
Labels: merge대기중⏱, 남수🐢, 리뷰완료😎, QA🍗

#119 [QA] 온보딩 입장하기 버튼 컬러 변경
  HikingClub/Feature/Onboarding/MainOnboardingViewController.swift
Labels: 상훈🐬, merge완료👍, QA🍗

#120 [QA] 위치 권한 및 홈 리스트 콘텐츠 별 가이드 문구 변경
  HikingClub/Feature/Home/HomeViewController.swift
  HikingClub/Feature/Home/HomeViewModel.swift
  HikingClub/Feature/Search/View/EmptyView.swift
Labels: merge대기중⏱, 피드백반영완료🙆🏻‍♂️, 상훈🐬, QA🍗
